module.exports = {
  apps: [
    {
      name: 'trade-assistant-agent',
      script: 'apps/service-agent/dist/index.js',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        HOST: '0.0.0.0',
        DASHSCOPE_API_KEY: 'sk-469ae5a3119e49e9afaadcd4f66980f5',
        DASHSCOPE_BASE_URL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        GOOGLE_API_KEY: 'AIzaSyCV_75iN7AEtYx4C4t-jz6HIqyGWj8pHck',
        GOOGLE_SEARCH_ENGINE_ID: '11dd97b987e454433',
        CSE_DATE: 'm18',
        CSE_MAX_PER_MIN: '40',
        USE_REAL_API: 'true',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
        HOST: '0.0.0.0',
        DASHSCOPE_API_KEY: 'sk-469ae5a3119e49e9afaadcd4f66980f5',
        DASHSCOPE_BASE_URL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        GOOGLE_API_KEY: 'AIzaSyCV_75iN7AEtYx4C4t-jz6HIqyGWj8pHck',
        GOOGLE_SEARCH_ENGINE_ID: '11dd97b987e454433',
        CSE_DATE: 'm18',
        CSE_MAX_PER_MIN: '40',
        USE_REAL_API: 'true',
      },
      env_file: '.env.local',
      error_file: './logs/agent-error.log',
      out_file: './logs/agent-out.log',
      log_file: './logs/agent-combined.log',
      time: true,
      max_restarts: 5,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'trade-assistant-web',
      script: './node_modules/.bin/next',
      args: 'start',
      cwd: './apps/web',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: '0.0.0.0',
        NEXT_PUBLIC_API_URL: 'https://3001-ibr8pve55krqf22np4xrh-6532622b.e2b.dev',
        AGENT_API_URL: 'https://3001-ibr8pve55krqf22np4xrh-6532622b.e2b.dev',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: '0.0.0.0',
        NEXT_PUBLIC_API_URL: 'https://3001-ibr8pve55krqf22np4xrh-6532622b.e2b.dev',
        AGENT_API_URL: 'https://3001-ibr8pve55krqf22np4xrh-6532622b.e2b.dev',
      },
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      log_file: './logs/web-combined.log',
      time: true,
      max_restarts: 5,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
  ],
};